### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by akiramitsu** [LevPasha/instabot.py#211] opened 2016-10-06 12:23 UTC
Traceback (most recent call last):
  File "C:\IG\example.py", line 18, in <module>
    log_mod=0)
  File "C:\IG\instabot.py", line 157, in __init__
    self.populate_user_blacklist()
  File "C:\IG\instabot.py", line 167, in populate_user_blacklist
    id_user = all_data['user']['media']['nodes'][0]['owner']['id']
IndexError: list index out of range

please help me

**Comment by haayhappen** [comment] 2016-10-06 12:51
duplicate of  #200

**Closed** 2016-10-06 14:25 UTC
